USE MCFGA_BIZ_DEMO09102024
GO

-- ============================================
-- ใช้ T_SALESORDERH อยากทราบยอดรายการ SALES แยกตามลูกค้าแต่ละเจ้า
-- ============================================


SELECT DISTINCT
    CUSTOMERCODE
FROM
    T_SALESORDERH
WHERE
    CUSTOMERCODE IS NOT NULL;


SELECT DISTINCT COMPANY
FROM T_SALESORDERH;


SELECT
    H.CUSTOMERCODE,
    H.CURRENCYCODE,
    SUM(D.UNITPRICE * D.QTY) AS TOTAL_SALES
FROM
    T_SALESORDERH H
        INNER JOIN T_SALESORDERD D ON H.VOUCHERNO = D.VOUCHERNO
GROUP BY
    H.CUSTOMERCODE, H.CURRENCYCODE
ORDER BY
    TOTAL_SALES DESC;


