USE MCFGA_BIZ_DEMO09102024
GO



SELECT
    VOUCHERNO,
    INPDATE,
    WAREHOUSE,
    T.NAME AS [WAREHOUSE],
    GOODSCODE,
    S.NAME AS [PRODUCT_NAME],
    QTY,
    UNITPRICE,
    INPAMOUNT_SC
FROM
    T_SALESORDERD D
        INNER JOIN M_GOODS AS S
            ON D.GOODSCODE = S.CODE
        INNER JOIN M_DEPARTMENT AS T
            ON WAREHOUSE = T.CODE;


