USE MCFGA_BIZ_DEMO09102024
GO


SELECT
    H.VOUCHERNO,
    H.TOTALAMOUNT_SC,
    D.VOUCHERNO,
    D.INPAMOUNT_SC,
    H.TOTALAMOUNT_SC - D.INPAMOUNT_SC AS [DIFF_SC]
FROM
    T_SALESORDERD D
        INNER JOIN T_SALESORDERH AS H
            ON D.VOUCHERNO = H.VOUCHERNO;
